# Generated by Django 4.2 on 2024-04-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0002_portfolio_alter_student_major_project_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='MedicalRecord',
        ),
    ]
