# Generated by Django 4.2 on 2024-04-02 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0005_remove_project_portfolio_remove_student_portfolio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Medication',
        ),
    ]
