# Generated by Django 4.2 on 2024-04-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0006_rename_student_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='name',
            new_name='medication_name',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='major',
        ),
        migrations.AddField(
            model_name='medication',
            name='calculation_unit',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('BSA', 'Body Mass Index'), ('None', 'None')], default=None, max_length=200),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('portfolio', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='nicurx_app.medicalrecord')),
            ],
        ),
    ]
