# Generated by Django 4.2 on 2024-04-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0007_medicalrecord_rename_name_medication_medication_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='email',
        ),
    ]
