# Generated by Django 4.2 on 2024-04-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0008_remove_medication_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='portfolio',
        ),
    ]
