# Generated by Django 4.2 on 2024-04-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0009_remove_patient_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(default=False, help_text='Height in centimeters'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(default=False, help_text='Weight in kilograms'),
        ),
    ]
