# Generated by Django 4.2 on 2024-04-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0010_patient_height_patient_is_active_patient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.FloatField(default=1.0, help_text='Height in centimeters'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Weight in kilograms'),
        ),
    ]
