# Generated by Django 4.2 on 2024-04-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0011_alter_patient_height_alter_patient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
    ]
