# Generated by Django 4.2 on 2024-04-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0012_patient_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
