# Generated by Django 4.2 on 2024-04-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0014_alter_patient_first_name_alter_patient_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.AddField(
            model_name='medication',
            name='evidence_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='resource_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='calculation_unit',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('BSA', 'Body Mass Index'), ('Rate', 'Rate'), ('None', 'None')], default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='nicurx_app.medicationprofile'),
        ),
    ]
