# Generated by Django 4.2 on 2024-04-04 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0016_patient_medication_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medication_profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nicurx_app.medicationprofile'),
        ),
    ]
