# Generated by Django 4.2 on 2024-04-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0019_alter_medication_medication_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='medication_profile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medication_profile',
        ),
    ]
