# Generated by Django 4.2 on 2024-04-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0021_medication_medication_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationprofile',
            name='high_risk',
            field=models.BooleanField(default=False),
        ),
    ]
