# Generated by Django 4.2 on 2024-04-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0022_medicationprofile_high_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationprofile',
            name='high_risk',
        ),
        migrations.AddField(
            model_name='medication',
            name='high_risk',
            field=models.BooleanField(default=False),
        ),
    ]
