# Generated by Django 4.2 on 2024-04-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0024_medicationprofile_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
