# Generated by Django 4.2 on 2024-04-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0025_medicationprofile_is_active_alter_patient_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationprofile',
            name='number_medications',
            field=models.IntegerField(null=True),
        ),
    ]
