# Generated by Django 4.2 on 2024-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0027_remove_medicationprofile_number_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
