# Generated by Django 4.2 on 2024-04-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0032_remove_patient_user_supervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='calculation_unit',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('BSA', 'Body Mass Index')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='medication',
            name='resource_link',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
