# Generated by Django 4.2 on 2024-04-18 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nicurx_app', '0036_remove_medicationprofile_has_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationdosage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosages', to='nicurx_app.medicationprofile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
